server {
    listen 8080;
    server_name _;

    server_tokens off;

    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 'core:ok:stage';
    }

    location / {
        add_header Content-Type text/plain;
        return 200 'core service (stage baseline)';
    }
}
