upstream core_upstream {
    server core:8080;
}

upstream agent_upstream {
    server agent:8087;
}

server {
    listen 80;
    server_name _;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 'proxy:ok';
    }

    location /agent/ {
        proxy_pass http://agent_upstream/;
    }

    location / {
        proxy_pass http://core_upstream/;
    }
}
