package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// makeMinecraftPayload builds a minimal payload with env_vars and port_reservations
// so that buildInstanceTemplateValues populates PORT_GAME, SERVER_NAME, etc.
func makeMinecraftPayload(templateKey string, extras map[string]any) map[string]any {
	payload := map[string]any{
		"template_key": templateKey,
		"env_vars": []any{
			map[string]any{"key": "SERVER_NAME", "value": "Test Server"},
			map[string]any{"key": "MAX_PLAYERS", "value": "20"},
		},
		"secrets": []any{
			map[string]any{"key": "RCON_PASSWORD", "value": "secret"},
			map[string]any{"key": "SERVER_PASSWORD", "value": ""},
		},
		"port_reservations": []any{
			map[string]any{"role": "GAME", "port": "25565"},
			map[string]any{"role": "RCON", "port": "25575"},
		},
	}
	for k, v := range extras {
		payload[k] = v
	}
	return payload
}

func makeBedrockPayload(extras map[string]any) map[string]any {
	payload := map[string]any{
		"template_key": "minecraft_bedrock",
		"env_vars": []any{
			map[string]any{"key": "SERVER_NAME", "value": "Bedrock Server"},
			map[string]any{"key": "MAX_PLAYERS", "value": "10"},
		},
		"secrets": []any{
			map[string]any{"key": "SERVER_PASSWORD", "value": ""},
		},
		"port_reservations": []any{
			map[string]any{"role": "GAME", "port": "19132"},
		},
	}
	for k, v := range extras {
		payload[k] = v
	}
	return payload
}

// --- isMinecraftTemplate ---

func TestIsMinecraftTemplateVanilla(t *testing.T) {
	if !isMinecraftTemplate(map[string]any{"template_key": "minecraft_vanilla_all"}) {
		t.Fatal("expected vanilla to be Minecraft")
	}
}

func TestIsMinecraftTemplatePaper(t *testing.T) {
	if !isMinecraftTemplate(map[string]any{"template_key": "minecraft_paper_all"}) {
		t.Fatal("expected paper to be Minecraft")
	}
}

func TestIsMinecraftTemplateBedrock(t *testing.T) {
	if !isMinecraftTemplate(map[string]any{"template_key": "minecraft_bedrock"}) {
		t.Fatal("expected bedrock to be Minecraft")
	}
}

func TestIsMinecraftTemplateNonMinecraft(t *testing.T) {
	if isMinecraftTemplate(map[string]any{"template_key": "cs2"}) {
		t.Fatal("cs2 should not be Minecraft")
	}
}

// --- isMinecraftBedrockTemplate ---

func TestIsMinecraftBedrockTemplateDetected(t *testing.T) {
	if !isMinecraftBedrockTemplate(map[string]any{"template_key": "minecraft_bedrock"}) {
		t.Fatal("expected bedrock detection")
	}
}

func TestIsMinecraftBedrockTemplateViaGameType(t *testing.T) {
	if !isMinecraftBedrockTemplate(map[string]any{"game_type": "minecraft_bedrock"}) {
		t.Fatal("expected bedrock via game_type")
	}
}

func TestIsMinecraftBedrockTemplateVanillaNotBedrock(t *testing.T) {
	if isMinecraftBedrockTemplate(map[string]any{"template_key": "minecraft_vanilla_all"}) {
		t.Fatal("vanilla must not be detected as bedrock")
	}
}

func TestIsMinecraftBedrockTemplatePaperNotBedrock(t *testing.T) {
	if isMinecraftBedrockTemplate(map[string]any{"template_key": "minecraft_paper_all"}) {
		t.Fatal("paper must not be detected as bedrock")
	}
}

// --- setServerProperty ---

func TestSetServerPropertyUpdatesExisting(t *testing.T) {
	lines := []string{"# comment", "server-port=25565", "max-players=20"}
	lines = setServerProperty(lines, "server-port", "25566")
	if lines[1] != "server-port=25566" {
		t.Fatalf("expected server-port=25566, got %q", lines[1])
	}
	if len(lines) != 3 {
		t.Fatalf("expected 3 lines, got %d", len(lines))
	}
}

func TestSetServerPropertyAppendsWhenMissing(t *testing.T) {
	lines := []string{"# comment", "max-players=20"}
	lines = setServerProperty(lines, "server-port", "25565")
	last := lines[len(lines)-1]
	if last != "server-port=25565" {
		t.Fatalf("expected appended entry, got %q", last)
	}
}

func TestSetServerPropertyPreservesComments(t *testing.T) {
	lines := []string{"#Generated by Minecraft", "server-port=25565"}
	lines = setServerProperty(lines, "server-port", "25566")
	if lines[0] != "#Generated by Minecraft" {
		t.Fatalf("comment was destroyed: %q", lines[0])
	}
}

func TestSetServerPropertyCaseInsensitiveKey(t *testing.T) {
	lines := []string{"Server-Port=25565"}
	lines = setServerProperty(lines, "server-port", "25566")
	if lines[0] != "server-port=25566" {
		t.Fatalf("expected updated line, got %q", lines[0])
	}
}

// --- parsePropertyLines ---

func TestParsePropertyLinesStripsTrailingBlank(t *testing.T) {
	lines := parsePropertyLines("a=1\nb=2\n")
	if len(lines) != 2 {
		t.Fatalf("expected 2 lines, got %d: %v", len(lines), lines)
	}
}

func TestParsePropertyLinesNormalisesWindowsLineEndings(t *testing.T) {
	lines := parsePropertyLines("a=1\r\nb=2\r\n")
	if len(lines) != 2 || lines[0] != "a=1" || lines[1] != "b=2" {
		t.Fatalf("unexpected lines: %v", lines)
	}
}

func TestParsePropertyLinesEmptyInput(t *testing.T) {
	lines := parsePropertyLines("")
	if len(lines) != 0 {
		t.Fatalf("expected empty slice, got %v", lines)
	}
}

// --- ensureMinecraftServerProperties: Java ---

func TestEnsureMinecraftServerPropertiesVanillaFreshInstall(t *testing.T) {
	dir := t.TempDir()
	payload := makeMinecraftPayload("minecraft_vanilla_all", nil)

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	assertProperty(t, content, "server-port", "25565")
	assertProperty(t, content, "max-players", "20")
	assertProperty(t, content, "motd", "Test Server")
	assertProperty(t, content, "enable-rcon", "true")
	assertProperty(t, content, "rcon.password", "secret")
	assertProperty(t, content, "rcon.port", "25575")
	assertProperty(t, content, "server-password", "")
}

func TestEnsureMinecraftServerPropertiesPaperFreshInstall(t *testing.T) {
	dir := t.TempDir()
	payload := makeMinecraftPayload("minecraft_paper_all", nil)

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	assertProperty(t, content, "server-port", "25565")
	assertProperty(t, content, "enable-rcon", "true")
}

func TestEnsureMinecraftServerPropertiesJavaUpdatesExisting(t *testing.T) {
	dir := t.TempDir()
	existing := "#Minecraft server properties\nserver-port=19999\nmax-players=5\n"
	mustWriteFile(filepath.Join(dir, "server.properties"), existing)

	payload := makeMinecraftPayload("minecraft_vanilla_all", nil)
	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	assertProperty(t, content, "server-port", "25565")
	assertProperty(t, content, "max-players", "20")
	if !strings.Contains(content, "#Minecraft server properties") {
		t.Fatal("comment was not preserved")
	}
}

func TestEnsureMinecraftServerPropertiesNoBedrockPortV6ForJava(t *testing.T) {
	dir := t.TempDir()
	payload := makeMinecraftPayload("minecraft_vanilla_all", nil)

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	if strings.Contains(content, "server-portv6") {
		t.Fatal("Java server must not contain server-portv6")
	}
}

func TestEnsureMinecraftServerPropertiesJavaEnablesQuery(t *testing.T) {
	dir := t.TempDir()
	payload := makeMinecraftPayload("minecraft_vanilla_all", nil)

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	assertProperty(t, content, "enable-query", "true")
}

func TestEnsureMinecraftServerPropertiesJavaSetsQueryPortSameAsGamePort(t *testing.T) {
	dir := t.TempDir()
	payload := makeMinecraftPayload("minecraft_vanilla_all", nil)

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	assertProperty(t, content, "query.port", "25565")
}

func TestEnsureMinecraftServerPropertiesJavaSetsServerIPFromNodeIP(t *testing.T) {
	dir := t.TempDir()
	payload := makeMinecraftPayload("minecraft_vanilla_all", map[string]any{
		"node_ip": "203.0.113.42",
	})

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	assertProperty(t, content, "server-ip", "203.0.113.42")
}

func TestEnsureMinecraftServerPropertiesJavaNoServerIPWhenMissing(t *testing.T) {
	dir := t.TempDir()
	payload := makeMinecraftPayload("minecraft_vanilla_all", nil)

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "server-ip=") && strings.TrimSpace(line) != "server-ip=" {
			t.Fatalf("server-ip must not be set when no IP is in payload, got: %q", line)
		}
	}
}

func TestEnsureMinecraftServerPropertiesNoRconForBedrock(t *testing.T) {
	dir := t.TempDir()
	payload := makeBedrockPayload(nil)

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	if strings.Contains(content, "enable-rcon") {
		t.Fatal("Bedrock server must not contain enable-rcon")
	}
	if strings.Contains(content, "rcon.password") {
		t.Fatal("Bedrock server must not contain rcon.password")
	}
}

func TestEnsureMinecraftServerPropertiesBedrockNoQuerySettings(t *testing.T) {
	dir := t.TempDir()
	payload := makeBedrockPayload(map[string]any{"node_ip": "203.0.113.42"})

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "enable-query=") {
			t.Fatalf("Bedrock must not contain enable-query, got: %q", line)
		}
		if strings.HasPrefix(trimmed, "query.port=") {
			t.Fatalf("Bedrock must not contain query.port, got: %q", line)
		}
		if strings.HasPrefix(trimmed, "server-ip=") && trimmed != "server-ip=" {
			t.Fatalf("Bedrock must not contain server-ip, got: %q", line)
		}
	}
}

// --- ensureMinecraftServerProperties: Bedrock ---

func TestEnsureMinecraftServerPropertiesBedrockFreshInstall(t *testing.T) {
	dir := t.TempDir()
	payload := makeBedrockPayload(nil)

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	assertProperty(t, content, "server-port", "19132")
	assertProperty(t, content, "server-portv6", "19132")
	assertProperty(t, content, "server-name", "Bedrock Server")
	assertProperty(t, content, "max-players", "10")
}

func TestEnsureMinecraftServerPropertiesBedrockUpdatesExisting(t *testing.T) {
	dir := t.TempDir()
	existing := "server-port=19132\nserver-name=Old Name\n"
	mustWriteFile(filepath.Join(dir, "server.properties"), existing)

	payload := makeBedrockPayload(nil)
	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content := mustReadFile(t, filepath.Join(dir, "server.properties"))
	assertProperty(t, content, "server-name", "Bedrock Server")
}

// --- skip for non-Minecraft ---

func TestEnsureMinecraftServerPropertiesSkipsNonMinecraft(t *testing.T) {
	dir := t.TempDir()
	payload := map[string]any{"template_key": "cs2"}

	if err := ensureMinecraftServerProperties(dir, payload); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "server.properties")); !os.IsNotExist(err) {
		t.Fatal("server.properties must NOT be created for non-Minecraft server")
	}
}

// helpers

func mustReadFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile %s: %v", path, err)
	}
	return string(b)
}

func mustWriteFile(path, content string) {
	if err := os.WriteFile(path, []byte(content), 0o640); err != nil {
		panic(err)
	}
}

// assertProperty checks that the file content contains "key=value".
func assertProperty(t *testing.T, content, key, value string) {
	t.Helper()
	want := key + "=" + value
	for _, line := range strings.Split(content, "\n") {
		if strings.TrimSpace(line) == want {
			return
		}
	}
	t.Fatalf("expected %q in server.properties:\n%s", want, content)
}
