<?php

declare(strict_types=1);

namespace App\Extension\Twig;

use App\Entity\User;
use App\Repository\InvoicePreferencesRepository;
use App\Repository\NotificationRepository;
use Symfony\Component\HttpFoundation\RequestStack;
use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

final class PortalContextTwigExtension extends AbstractExtension
{
    private const TRANSLATIONS = [
        'en' => [
            'global_search_placeholder' => 'Search customers, instances, domains, tickets',
            'notifications' => 'Notifications',
            'activity' => 'Activity',
            'dashboard' => 'Dashboard',
            'toggle_theme' => 'Toggle theme',
            'search_help' => 'Press / to search',
            'no_results' => 'No results yet.',
            'search_title' => 'Global search',
            'mark_read' => 'Mark as read',
            'unread' => 'Unread',
            'read' => 'Read',
            'language' => 'Language',
            'public_portal' => 'Public Portal',
            'public_portal_tagline' => 'Public Portal · vNext',
            'toggle_sidebar' => 'Toggle sidebar',
            'hosting_updates_title' => 'Hosting updates',
            'hosting_updates_subtitle' => 'Downloads, changelog, docs',
            'login' => 'Login',
            'register' => 'Register',
            'welcome_kicker' => 'Welcome to',
            'welcome_title' => 'Your hosting portal starts here.',
            'welcome_description' => 'Explore public service updates, browse available servers, or sign in to manage your account.',
            'view_status' => 'View status',
            'status_overview' => 'Status overview',
            'status_overview_description' => 'Check system uptime, maintenance windows, and incident reports.',
            'go_to_status' => 'Go to status →',
            'server_directory' => 'Server directory',
            'server_directory_description' => 'Browse featured public servers or find new experiences.',
            'browse_servers' => 'Browse servers →',
            'downloads_docs' => 'Downloads & docs',
            'downloads_docs_description' => 'Get launchers, configuration files, and documentation.',
            'view_downloads' => 'View downloads →',
            'changelog' => 'Changelog',
            'changelog_description' => 'Latest improvements and fixes.',
            'pulling_releases_from' => 'Pulling releases from',
            'unscheduled' => 'Unscheduled',
            'no_details_provided' => 'No details provided.',
            'no_changelog_entries' => 'No changelog entries yet.',
            'docs' => 'Docs',
            'docs_title' => 'Docs & Knowledge Base',
            'docs_description' => 'Browse FAQs and troubleshooting guides.',
            'no_docs_in_category' => 'No articles in this category yet.',
            'no_public_docs' => 'No public docs available yet.',
            'back_to_docs' => 'Back to Docs',
            'downloads' => 'Downloads',
            'downloads_description' => 'Grab the latest launchers, configs, and resources.',
            'download' => 'Download',
            'version' => 'Version',
            'size' => 'Size',
            'action' => 'Action',
            'no_downloads_available' => 'No downloads available yet.',
            'server_directory_title' => 'Server Directory',
            'server_directory_intro' => 'Browse public servers for this site.',
            'search' => 'Search',
            'server_search_placeholder' => 'Server name or game',
            'game' => 'Game',
            'all_games' => 'All games',
            'status' => 'Status',
            'all' => 'All',
            'filter' => 'Filter',
            'server' => 'Server',
            'address' => 'Address',
            'players' => 'Players',
            'map' => 'Map',
            'last_update' => 'Last update',
            'join' => 'Join',
            'no_public_servers' => 'No public servers available.',
            'service_status' => 'Service Status',
            'service_status_description' => 'Live view of public-facing components.',
            'component' => 'Component',
            'type' => 'Type',
            'last_checked' => 'Last Checked',
            'no_public_components' => 'No public components configured yet.',
            'current_incidents' => 'Current Incidents',
            'current_incidents_description' => 'Active issues and their latest updates.',
            'no_public_updates' => 'No public updates yet.',
            'no_active_incidents' => 'No active incidents.',
            'maintenance' => 'Maintenance',
            'maintenance_description' => 'Upcoming and in-progress maintenance windows.',
            'in_progress' => 'In progress',
            'upcoming' => 'Upcoming',
            'no_scheduled_maintenance' => 'No scheduled maintenance.',
            'status_operational' => 'Operational',
            'status_degraded' => 'Degraded',
            'status_outage' => 'Outage',
            'status_maintenance' => 'Maintenance',
            'status_investigating' => 'Investigating',
            'status_identified' => 'Identified',
            'status_monitoring' => 'Monitoring',
            'status_resolved' => 'Resolved',
            'status_online' => 'Online',
            'status_offline' => 'Offline',
            'status_unknown' => 'Unknown',
            'status_error' => 'Error',
            'welcome_back' => 'Welcome back',
            'login_description' => 'Sign in to manage your portal access.',
            'email_address' => 'Email address',
            'email_placeholder' => 'you@example.com',
            'password' => 'Password',
            'password_placeholder' => 'Your password',
            'log_in' => 'Log in',
            'first_time_here' => 'First time here?',
            'register_intro' => 'Create an account to access services, tickets, and billing.',
            'register_now' => 'Register now',
            'need_help' => 'Need help?',
            'login_help' => 'Contact %site% support for login assistance.',
            'support_available' => 'Support available 24/7',
            'create_account' => 'Create account',
            'create_account_title' => 'Create your hosting account',
            'create_account_description' => 'Register for access to the customer portal and services.',
            'registration_success' => 'Thanks for registering! Check your inbox to verify your email address before logging in.',
            'password_minimum' => 'Minimum 8 characters',
            'confirm_password' => 'Confirm password',
            'confirm_password_placeholder' => 'Re-enter password',
            'repeat_password_placeholder' => 'Repeat password',
            'terms_agree' => 'I agree to the',
            'terms_of_service' => 'Terms of Service',
            'privacy_policy' => 'Privacy Policy',
            'what_happens_next' => 'What happens next?',
            'next_step_verify_email' => 'Verify your email to activate the account.',
            'next_step_login' => 'Log in to manage your hosting services.',
            'next_step_support' => 'Access support and billing in the customer portal.',
            'onboarding_help' => 'Contact %site% support for onboarding assistance.',
            'no_blocks_available' => 'No blocks available.',
            'install' => 'Install',
            'installer' => 'Installer',
            'installer_description' => 'Connect a database and create the first admin account.',
            'installation_completed' => 'Installation completed! You can now',
            'log_in_with_admin' => 'log in',
            'with_admin_account' => 'with your admin account.',
            'admin_account_exists' => 'An admin account already exists. Installation is locked. You can proceed to',
            'step_of' => 'Step %current% of %total%',
            'database_settings' => 'Database settings',
            'site_defaults' => 'Site defaults',
            'admin_account' => 'Admin account',
            'driver' => 'Driver',
            'database_name' => 'Database name',
            'host' => 'Host',
            'port' => 'Port',
            'username' => 'Username',
            'optional' => 'Optional',
            'sqlite_path' => 'SQLite path',
            'sqlite_helper' => 'Used only when SQLite is selected.',
            'site_name' => 'Site name',
            'site_host' => 'Site host',
            'admin_email' => 'Admin email',
            'back' => 'Back',
            'test_connection' => 'Test MySQL/SQLite connection',
            'next' => 'Next',
            'run_installer' => 'Run installer',
            'server_requirements' => 'Server requirements',
            'php_version' => 'PHP version',
            'loaded_php_extensions' => 'Loaded PHP extensions',
            'no_php_extensions' => 'No PHP extensions detected.',
            'activity_title' => 'Activity feed',
            'cms_pages_title' => 'CMS Pages',
            'cms_pages_description' => 'Manage page slugs, publishing status, and content block counts.',
            'cms_pages_tracked_suffix' => 'tracked',
            'cms_page_singular' => 'page',
            'cms_page_plural' => 'pages',
            'refresh' => 'Refresh',
            'total_pages' => 'Total Pages',
            'published' => 'Published',
            'live_pages_visible' => 'Live pages visible to customers',
            'blocks' => 'Blocks',
            'structured_content_blocks' => 'Structured content blocks',
            'pages_overview' => 'Pages Overview',
            'pages_overview_description' => 'Track the pages in your CMS and jump into block editing.',
            'create_cms_page' => 'Create a CMS page',
            'create_cms_page_description' => 'Define a slug and publishing status for the new page.',
            'please_fix_following' => 'Please fix the following:',
            'title' => 'Title',
            'slug' => 'Slug',
            'publish_immediately' => 'Publish immediately',
            'create_page' => 'Create page',
            'cms_page_title_placeholder' => 'Homepage, Pricing, FAQ',
            'cms_page_slug_placeholder' => 'pricing',
            'page' => 'Page',
            'status' => 'Status',
            'updated' => 'Updated',
            'actions' => 'Actions',
            'draft' => 'Draft',
            'manage_blocks' => 'Manage Blocks',
            'no_cms_pages' => 'No CMS pages yet. Create the first page to get started.',
            'cms_page_manage_blocks_description' => 'Manage content blocks for',
            'back_to_pages' => 'Back to pages',
            'cms_template_title' => 'CMS Templates',
            'cms_template_description' => 'Choose a ready-to-use layout set and apply it to this site.',
            'select_cms_template' => 'CMS template',
            'select_cms_template_placeholder' => 'Select a template',
            'cms_template_apply_now' => 'Apply template pages now',
            'cms_template_apply_help' => 'Applies missing pages and blocks for the selected template. Existing pages are kept.',
            'cms_template_selected_success' => 'CMS template saved.',
            'cms_template_pages_included' => 'Includes pages:',
            'selected' => 'Selected',
            'content_blocks' => 'Content Blocks',
            'content_blocks_description' => 'Arrange and edit structured content for this page.',
            'order' => 'Order',
            'type' => 'Type',
            'preview' => 'Preview',
            'no_blocks_yet' => 'No blocks yet. Add the first block for this page.',
            'add_content_block' => 'Add content block',
            'add_content_block_description' => 'Keep blocks modular for flexible page layouts.',
            'block_type' => 'Block type',
            'block_type_placeholder' => 'hero, feature-grid, faq',
            'content' => 'Content',
            'block_content_placeholder' => 'Markdown or HTML content',
            'server_block_settings' => 'Server block settings',
            'game_filter' => 'Game filter',
            'game_filter_placeholder' => 'valheim',
            'limit' => 'Limit',
            'show_players' => 'Show players',
            'show_join_button' => 'Show join button',
            'server_block_settings_help' => 'These settings apply to <strong>server_list</strong> and <strong>server_featured</strong> blocks only.',
            'add_block' => 'Add block',
            'user_management_title' => 'User management',
            'user_management_description' => 'Review users and adjust portal language preferences.',
            'email' => 'Email',
            'created' => 'Created',
            'portal_language' => 'Portal language',
            'invoice_locale' => 'Invoice locale',
            'save' => 'Save',
            'defaults_applied' => 'Defaults applied',
            'no_users_found' => 'No users found.',
            'profile_billing_title' => 'Profile & Billing',
            'profile_billing_description' => 'Manage your contact details, invoice address, and delivery preferences.',
            'invoice_ready' => 'Invoice ready',
            'customer_profile_title' => 'Customer Profile',
            'customer_profile_description' => 'Use the address below for invoices and contracts.',
            'required' => 'Required',
            'profile_saved_successfully' => 'Profile saved successfully.',
            'first_name' => 'First name',
            'last_name' => 'Last name',
            'street_address' => 'Street address',
            'postal_code' => 'Postal code',
            'city' => 'City',
            'country' => 'Country',
            'phone_optional' => 'Phone (optional)',
            'company_optional' => 'Company (optional)',
            'vat_id_optional' => 'VAT ID (optional)',
            'vat_id_help' => 'Use your full VAT ID including the country code (e.g. DE123456789).',
            'save_profile' => 'Save profile',
            'invoice_preferences_title' => 'Invoice Preferences',
            'invoice_preferences_description' => 'Choose delivery channels and your default payment option.',
            'preferences' => 'Preferences',
            'preferences_updated' => 'Preferences updated.',
            'email_delivery_label' => 'Email me invoices when they are issued.',
            'pdf_download_history_label' => 'Keep PDFs available in my download history.',
            'default_payment_method' => 'Default payment method',
            'save_preferences' => 'Save preferences',
            'customer_dashboard_title' => 'Customer Dashboard',
            'customer_dashboard_welcome' => 'Welcome back,',
            'customer_dashboard_description' => 'Your services, usage, and support updates at a glance.',
            'customer_dashboard_card_game_servers' => 'Game Servers',
            'customer_dashboard_card_websites' => 'Websites',
            'customer_dashboard_card_databases' => 'Databases',
            'customer_dashboard_card_support_tickets' => 'Support Tickets',
            'customer_dashboard_card_active' => 'Active',
            'customer_dashboard_card_hosted' => 'Hosted',
            'customer_dashboard_card_databases_total' => 'Databases total',
            'customer_dashboard_card_total' => 'Total',
            'customer_dashboard_my_game_servers' => 'My Game Servers',
            'customer_dashboard_manage_update' => 'Manage & update',
            'customer_dashboard_my_websites' => 'My Websites',
            'customer_dashboard_domains_files' => 'Domains & files',
            'customer_dashboard_my_databases' => 'My Databases',
            'customer_dashboard_db_management' => 'DB management',
            'customer_dashboard_billing_invoices' => 'Billing & Invoices',
            'customer_dashboard_view_pay_bills' => 'View & pay bills',
            'customer_dashboard_my_servers' => 'My Game Servers',
            'customer_dashboard_my_servers_description' => 'Status and quick actions for your instances.',
            'customer_dashboard_manage' => 'Manage',
            'customer_dashboard_no_instances' => 'No instances yet.',
            'customer_dashboard_latest_tickets' => 'Latest Support Tickets',
            'customer_dashboard_latest_tickets_description' => 'Track ticket status and response progress.',
            'customer_dashboard_no_tickets' => 'No tickets yet.',
            'customer_dashboard_view_all_tickets' => 'View all tickets',
            'customer_dashboard_resource_usage' => 'Resource Usage',
            'customer_dashboard_resource_usage_description' => 'Overall service usage across your resources.',
            'customer_dashboard_cpu_usage' => 'CPU Usage',
            'customer_dashboard_ram_usage' => 'RAM Usage',
            'customer_dashboard_disk_usage' => 'Disk Usage',
            'customer_databases_title' => 'Databases',
            'customer_databases_description' => 'Overview of your database services and access details.',
            'customer_databases_overview' => 'Database Overview',
            'customer_databases_overview_description' => 'Track database connection details and recent updates.',
            'customer_databases_empty' => 'No databases provisioned yet.',
            'customer_databases_table_name' => 'Database',
            'customer_databases_table_engine' => 'Engine',
            'customer_databases_table_host' => 'Host',
            'customer_databases_table_user' => 'User',
            'customer_databases_table_updated' => 'Updated',
        ],
        'de' => [
            'global_search_placeholder' => 'Kunden, Instanzen, Domains, Tickets suchen',
            'notifications' => 'Benachrichtigungen',
            'activity' => 'Aktivität',
            'dashboard' => 'Dashboard',
            'toggle_theme' => 'Design umschalten',
            'search_help' => 'Mit / suchen',
            'no_results' => 'Noch keine Ergebnisse.',
            'search_title' => 'Globale Suche',
            'mark_read' => 'Als gelesen markieren',
            'unread' => 'Ungelesen',
            'read' => 'Gelesen',
            'language' => 'Sprache',
            'public_portal' => 'Öffentliches Portal',
            'public_portal_tagline' => 'Öffentliches Portal · vNext',
            'toggle_sidebar' => 'Seitenleiste umschalten',
            'hosting_updates_title' => 'Hosting-Updates',
            'hosting_updates_subtitle' => 'Downloads, Changelog, Doku',
            'login' => 'Login',
            'register' => 'Registrieren',
            'welcome_kicker' => 'Willkommen bei',
            'welcome_title' => 'Ihr Hosting-Portal startet hier.',
            'welcome_description' => 'Entdecken Sie Service-Updates, stöbern Sie verfügbare Server oder melden Sie sich an, um Ihr Konto zu verwalten.',
            'view_status' => 'Status anzeigen',
            'status_overview' => 'Statusübersicht',
            'status_overview_description' => 'Prüfen Sie Verfügbarkeit, Wartungsfenster und Vorfälle.',
            'go_to_status' => 'Zum Status →',
            'server_directory' => 'Serververzeichnis',
            'server_directory_description' => 'Stöbern Sie in öffentlichen Servern oder entdecken Sie neue Erlebnisse.',
            'browse_servers' => 'Server durchsuchen →',
            'downloads_docs' => 'Downloads & Doku',
            'downloads_docs_description' => 'Holen Sie sich Launcher, Konfigurationsdateien und Dokumentation.',
            'view_downloads' => 'Downloads anzeigen →',
            'changelog' => 'Changelog',
            'changelog_description' => 'Neueste Verbesserungen und Fixes.',
            'pulling_releases_from' => 'Veröffentlichungen von',
            'unscheduled' => 'Nicht terminiert',
            'no_details_provided' => 'Keine Details vorhanden.',
            'no_changelog_entries' => 'Noch keine Changelog-Einträge.',
            'docs' => 'Doku',
            'docs_title' => 'Doku & Wissensdatenbank',
            'docs_description' => 'Stöbern Sie in FAQs und Troubleshooting-Guides.',
            'no_docs_in_category' => 'Noch keine Artikel in dieser Kategorie.',
            'no_public_docs' => 'Noch keine öffentliche Doku verfügbar.',
            'back_to_docs' => 'Zurück zur Doku',
            'downloads' => 'Downloads',
            'downloads_description' => 'Holen Sie sich die neuesten Launcher, Konfigurationen und Ressourcen.',
            'download' => 'Download',
            'version' => 'Version',
            'size' => 'Größe',
            'action' => 'Aktion',
            'no_downloads_available' => 'Noch keine Downloads verfügbar.',
            'server_directory_title' => 'Serververzeichnis',
            'server_directory_intro' => 'Stöbern Sie in öffentlichen Servern dieser Seite.',
            'search' => 'Suche',
            'server_search_placeholder' => 'Servername oder Spiel',
            'game' => 'Spiel',
            'all_games' => 'Alle Spiele',
            'status' => 'Status',
            'all' => 'Alle',
            'filter' => 'Filtern',
            'server' => 'Server',
            'address' => 'Adresse',
            'players' => 'Spieler',
            'map' => 'Karte',
            'last_update' => 'Letztes Update',
            'join' => 'Beitreten',
            'no_public_servers' => 'Keine öffentlichen Server verfügbar.',
            'service_status' => 'Service-Status',
            'service_status_description' => 'Live-Ansicht der öffentlichen Komponenten.',
            'component' => 'Komponente',
            'type' => 'Typ',
            'last_checked' => 'Zuletzt geprüft',
            'no_public_components' => 'Noch keine öffentlichen Komponenten konfiguriert.',
            'current_incidents' => 'Aktuelle Vorfälle',
            'current_incidents_description' => 'Aktive Probleme und die neuesten Updates.',
            'no_public_updates' => 'Noch keine öffentlichen Updates.',
            'no_active_incidents' => 'Keine aktiven Vorfälle.',
            'maintenance' => 'Wartung',
            'maintenance_description' => 'Bevorstehende und laufende Wartungsfenster.',
            'in_progress' => 'Laufend',
            'upcoming' => 'Bevorstehend',
            'no_scheduled_maintenance' => 'Keine Wartungen geplant.',
            'status_operational' => 'Betriebsbereit',
            'status_degraded' => 'Eingeschränkt',
            'status_outage' => 'Ausfall',
            'status_maintenance' => 'Wartung',
            'status_investigating' => 'Untersuchung',
            'status_identified' => 'Identifiziert',
            'status_monitoring' => 'Überwachung',
            'status_resolved' => 'Behoben',
            'status_online' => 'Online',
            'status_offline' => 'Offline',
            'status_unknown' => 'Unbekannt',
            'status_error' => 'Fehler',
            'welcome_back' => 'Willkommen zurück',
            'login_description' => 'Melden Sie sich an, um Ihren Portalzugang zu verwalten.',
            'email_address' => 'E-Mail-Adresse',
            'email_placeholder' => 'you@example.com',
            'password' => 'Passwort',
            'password_placeholder' => 'Ihr Passwort',
            'log_in' => 'Einloggen',
            'first_time_here' => 'Erstes Mal hier?',
            'register_intro' => 'Erstellen Sie ein Konto für Services, Tickets und Abrechnung.',
            'register_now' => 'Jetzt registrieren',
            'need_help' => 'Hilfe benötigt?',
            'login_help' => 'Kontaktieren Sie den Support von %site% für Hilfe beim Login.',
            'support_available' => 'Support verfügbar rund um die Uhr',
            'create_account' => 'Konto erstellen',
            'create_account_title' => 'Erstellen Sie Ihr Hosting-Konto',
            'create_account_description' => 'Registrieren Sie sich für den Zugang zum Kundenportal und zu den Services.',
            'registration_success' => 'Danke für die Registrierung! Prüfen Sie Ihren Posteingang, um Ihre E-Mail-Adresse zu bestätigen, bevor Sie sich anmelden.',
            'password_minimum' => 'Mindestens 8 Zeichen',
            'confirm_password' => 'Passwort bestätigen',
            'confirm_password_placeholder' => 'Passwort erneut eingeben',
            'repeat_password_placeholder' => 'Passwort wiederholen',
            'terms_agree' => 'Ich stimme den',
            'terms_of_service' => 'Nutzungsbedingungen',
            'privacy_policy' => 'Datenschutzbestimmungen',
            'what_happens_next' => 'Wie geht es weiter?',
            'next_step_verify_email' => 'Bestätigen Sie Ihre E-Mail, um das Konto zu aktivieren.',
            'next_step_login' => 'Melden Sie sich an, um Ihre Hosting-Services zu verwalten.',
            'next_step_support' => 'Zugriff auf Support und Abrechnung im Kundenportal.',
            'onboarding_help' => 'Kontaktieren Sie den Support von %site% für Hilfe beim Onboarding.',
            'no_blocks_available' => 'Keine Blöcke verfügbar.',
            'install' => 'Installieren',
            'installer' => 'Installer',
            'installer_description' => 'Verbinden Sie eine Datenbank und erstellen Sie das erste Admin-Konto.',
            'installation_completed' => 'Installation abgeschlossen! Sie können sich jetzt',
            'log_in_with_admin' => 'einloggen',
            'with_admin_account' => 'mit Ihrem Admin-Konto.',
            'admin_account_exists' => 'Ein Admin-Konto existiert bereits. Die Installation ist gesperrt. Sie können fortfahren zu',
            'step_of' => 'Schritt %current% von %total%',
            'database_settings' => 'Datenbankeinstellungen',
            'site_defaults' => 'Standardwerte der Seite',
            'admin_account' => 'Admin-Konto',
            'driver' => 'Treiber',
            'database_name' => 'Datenbankname',
            'host' => 'Host',
            'port' => 'Port',
            'username' => 'Benutzername',
            'optional' => 'Optional',
            'sqlite_path' => 'SQLite-Pfad',
            'sqlite_helper' => 'Nur bei ausgewähltem SQLite.',
            'site_name' => 'Seitenname',
            'site_host' => 'Seiten-Host',
            'admin_email' => 'Admin-E-Mail',
            'back' => 'Zurück',
            'test_connection' => 'MySQL/SQLite-Verbindung testen',
            'next' => 'Weiter',
            'run_installer' => 'Installer ausführen',
            'server_requirements' => 'Serveranforderungen',
            'php_version' => 'PHP-Version',
            'loaded_php_extensions' => 'Geladene PHP-Erweiterungen',
            'no_php_extensions' => 'Keine PHP-Erweiterungen erkannt.',
            'activity_title' => 'Aktivitätsfeed',
            'cms_pages_title' => 'CMS-Seiten',
            'cms_pages_description' => 'Verwalten Sie Slugs, Veröffentlichungen und die Anzahl der Inhaltsblöcke.',
            'cms_pages_tracked_suffix' => 'im Blick',
            'cms_page_singular' => 'Seite',
            'cms_page_plural' => 'Seiten',
            'refresh' => 'Aktualisieren',
            'total_pages' => 'Seiten gesamt',
            'published' => 'Veröffentlicht',
            'live_pages_visible' => 'Live-Seiten sichtbar für Kunden',
            'blocks' => 'Blöcke',
            'structured_content_blocks' => 'Strukturierte Inhaltsblöcke',
            'pages_overview' => 'Seitenübersicht',
            'pages_overview_description' => 'Behalten Sie Ihre CMS-Seiten im Blick und springen Sie direkt in die Blockbearbeitung.',
            'create_cms_page' => 'CMS-Seite erstellen',
            'create_cms_page_description' => 'Definieren Sie einen Slug und den Veröffentlichungsstatus der neuen Seite.',
            'please_fix_following' => 'Bitte beheben Sie Folgendes:',
            'title' => 'Titel',
            'slug' => 'Slug',
            'publish_immediately' => 'Sofort veröffentlichen',
            'create_page' => 'Seite erstellen',
            'cms_page_title_placeholder' => 'Startseite, Preise, FAQ',
            'cms_page_slug_placeholder' => 'preise',
            'page' => 'Seite',
            'status' => 'Status',
            'updated' => 'Aktualisiert',
            'actions' => 'Aktionen',
            'draft' => 'Entwurf',
            'manage_blocks' => 'Blöcke verwalten',
            'no_cms_pages' => 'Noch keine CMS-Seiten. Erstellen Sie die erste Seite, um loszulegen.',
            'cms_page_manage_blocks_description' => 'Verwalten Sie Inhaltsblöcke für',
            'back_to_pages' => 'Zurück zu den Seiten',
            'cms_template_title' => 'CMS-Vorlagen',
            'cms_template_description' => 'Wählen Sie ein fertiges Layout-Set und wenden Sie es auf diese Seite an.',
            'select_cms_template' => 'CMS-Vorlage',
            'select_cms_template_placeholder' => 'Vorlage auswählen',
            'cms_template_apply_now' => 'Vorlagenseiten jetzt anwenden',
            'cms_template_apply_help' => 'Fügt fehlende Seiten und Blöcke der Vorlage hinzu. Vorhandene Seiten bleiben erhalten.',
            'cms_template_selected_success' => 'CMS-Vorlage gespeichert.',
            'cms_template_pages_included' => 'Enthält Seiten:',
            'selected' => 'Ausgewählt',
            'content_blocks' => 'Inhaltsblöcke',
            'content_blocks_description' => 'Ordnen und bearbeiten Sie strukturierte Inhalte für diese Seite.',
            'order' => 'Reihenfolge',
            'type' => 'Typ',
            'preview' => 'Vorschau',
            'no_blocks_yet' => 'Noch keine Blöcke. Fügen Sie den ersten Block für diese Seite hinzu.',
            'add_content_block' => 'Inhaltsblock hinzufügen',
            'add_content_block_description' => 'Halten Sie Blöcke modular für flexible Seitenlayouts.',
            'block_type' => 'Blocktyp',
            'block_type_placeholder' => 'hero, feature-grid, faq',
            'content' => 'Inhalt',
            'block_content_placeholder' => 'Markdown- oder HTML-Inhalt',
            'server_block_settings' => 'Serverblock-Einstellungen',
            'game_filter' => 'Spiel-Filter',
            'game_filter_placeholder' => 'valheim',
            'limit' => 'Limit',
            'show_players' => 'Spieler anzeigen',
            'show_join_button' => 'Beitreten-Button anzeigen',
            'server_block_settings_help' => 'Diese Einstellungen gelten nur für <strong>server_list</strong>- und <strong>server_featured</strong>-Blöcke.',
            'add_block' => 'Block hinzufügen',
            'user_management_title' => 'Benutzerverwaltung',
            'user_management_description' => 'Benutzer prüfen und Portalsprachen anpassen.',
            'email' => 'E-Mail',
            'created' => 'Erstellt',
            'portal_language' => 'Portalsprache',
            'invoice_locale' => 'Rechnungs-Locale',
            'save' => 'Speichern',
            'defaults_applied' => 'Standardwerte angewendet',
            'no_users_found' => 'Keine Benutzer gefunden.',
            'profile_billing_title' => 'Profil & Abrechnung',
            'profile_billing_description' => 'Verwalten Sie Kontaktdaten, Rechnungsadresse und Zustelloptionen.',
            'invoice_ready' => 'Rechnung bereit',
            'customer_profile_title' => 'Kundenprofil',
            'customer_profile_description' => 'Verwenden Sie die Adresse unten für Rechnungen und Verträge.',
            'required' => 'Pflichtfeld',
            'profile_saved_successfully' => 'Profil erfolgreich gespeichert.',
            'first_name' => 'Vorname',
            'last_name' => 'Nachname',
            'street_address' => 'Straße und Hausnummer',
            'postal_code' => 'Postleitzahl',
            'city' => 'Stadt',
            'country' => 'Land',
            'phone_optional' => 'Telefon (optional)',
            'company_optional' => 'Firma (optional)',
            'vat_id_optional' => 'USt-IdNr. (optional)',
            'vat_id_help' => 'Geben Sie Ihre vollständige USt-IdNr. inklusive Ländercode an (z. B. DE123456789).',
            'save_profile' => 'Profil speichern',
            'invoice_preferences_title' => 'Rechnungseinstellungen',
            'invoice_preferences_description' => 'Wählen Sie Zustellkanäle und Ihre bevorzugte Zahlungsmethode.',
            'preferences' => 'Einstellungen',
            'preferences_updated' => 'Einstellungen aktualisiert.',
            'email_delivery_label' => 'E-Mail-Benachrichtigung bei ausgestellten Rechnungen.',
            'pdf_download_history_label' => 'PDFs im Download-Verlauf verfügbar halten.',
            'default_payment_method' => 'Standard-Zahlungsmethode',
            'save_preferences' => 'Einstellungen speichern',
            'customer_dashboard_title' => 'Kunden-Dashboard',
            'customer_dashboard_welcome' => 'Willkommen zurück,',
            'customer_dashboard_description' => 'Ihre Services, Auslastung und Support-Updates auf einen Blick.',
            'customer_dashboard_card_game_servers' => 'Game-Server',
            'customer_dashboard_card_websites' => 'Websites',
            'customer_dashboard_card_databases' => 'Datenbanken',
            'customer_dashboard_card_support_tickets' => 'Support-Tickets',
            'customer_dashboard_card_active' => 'Aktiv',
            'customer_dashboard_card_hosted' => 'Gehostet',
            'customer_dashboard_card_databases_total' => 'Datenbanken gesamt',
            'customer_dashboard_card_total' => 'Gesamt',
            'customer_dashboard_my_game_servers' => 'Meine Game-Server',
            'customer_dashboard_manage_update' => 'Verwalten & aktualisieren',
            'customer_dashboard_my_websites' => 'Meine Websites',
            'customer_dashboard_domains_files' => 'Domains & Dateien',
            'customer_dashboard_my_databases' => 'Meine Datenbanken',
            'customer_dashboard_db_management' => 'DB-Verwaltung',
            'customer_dashboard_billing_invoices' => 'Abrechnung & Rechnungen',
            'customer_dashboard_view_pay_bills' => 'Rechnungen ansehen & zahlen',
            'customer_dashboard_my_servers' => 'Meine Game-Server',
            'customer_dashboard_my_servers_description' => 'Status und Schnellzugriff für Ihre Instanzen.',
            'customer_dashboard_manage' => 'Verwalten',
            'customer_dashboard_no_instances' => 'Noch keine Instanzen.',
            'customer_dashboard_latest_tickets' => 'Neueste Support-Tickets',
            'customer_dashboard_latest_tickets_description' => 'Status und Antwortfortschritt im Blick behalten.',
            'customer_dashboard_no_tickets' => 'Noch keine Tickets.',
            'customer_dashboard_view_all_tickets' => 'Alle Tickets anzeigen',
            'customer_dashboard_resource_usage' => 'Ressourcennutzung',
            'customer_dashboard_resource_usage_description' => 'Gesamtauslastung Ihrer Ressourcen.',
            'customer_dashboard_cpu_usage' => 'CPU-Auslastung',
            'customer_dashboard_ram_usage' => 'RAM-Auslastung',
            'customer_dashboard_disk_usage' => 'Festplatten-Auslastung',
            'customer_databases_title' => 'Datenbanken',
            'customer_databases_description' => 'Übersicht Ihrer Datenbank-Services und Zugangsdaten.',
            'customer_databases_overview' => 'Datenbank-Übersicht',
            'customer_databases_overview_description' => 'Behalten Sie Verbindungsdaten und aktuelle Updates im Blick.',
            'customer_databases_empty' => 'Noch keine Datenbanken eingerichtet.',
            'customer_databases_table_name' => 'Datenbank',
            'customer_databases_table_engine' => 'Engine',
            'customer_databases_table_host' => 'Host',
            'customer_databases_table_user' => 'Benutzer',
            'customer_databases_table_updated' => 'Aktualisiert',
        ],
    ];

    public function __construct(
        private readonly RequestStack $requestStack,
        private readonly NotificationRepository $notificationRepository,
        private readonly InvoicePreferencesRepository $invoicePreferencesRepository,
    ) {
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction('page_locale', [$this, 'pageLocale']),
            new TwigFunction('unread_notifications', [$this, 'unreadNotifications']),
            new TwigFunction('t', [$this, 'translate']),
        ];
    }

    public function pageLocale(): string
    {
        $request = $this->requestStack->getCurrentRequest();
        $requestedLocale = null;

        if ($request !== null) {
            $requestedLocale = $request->query->get('lang') ?? $request->query->get('locale');
        }

        if (is_string($requestedLocale)) {
            $requestedLocale = strtolower(trim($requestedLocale));
            if (in_array($requestedLocale, ['de', 'en'], true)) {
                return $requestedLocale;
            }
        }

        $actor = $request?->attributes->get('current_user');

        if (!$actor instanceof User) {
            $cookieLocale = $request?->cookies->get('portal_language');

            if (is_string($cookieLocale) && in_array($cookieLocale, ['de', 'en'], true)) {
                return $cookieLocale;
            }

            return 'de';
        }

        $preferences = $this->invoicePreferencesRepository->findOneByCustomer($actor);
        return $preferences?->getPortalLanguage() ?? 'de';
    }

    public function unreadNotifications(): int
    {
        $request = $this->requestStack->getCurrentRequest();
        $actor = $request?->attributes->get('current_user');

        if (!$actor instanceof User) {
            return 0;
        }

        return $this->notificationRepository->findUnreadCount($actor);
    }

    public function translate(string $key, ?string $locale = null): string
    {
        $resolvedLocale = $locale ?? $this->pageLocale();
        $dictionary = self::TRANSLATIONS[$resolvedLocale] ?? self::TRANSLATIONS['en'];

        return $dictionary[$key] ?? $key;
    }
}
